version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "8000:80"
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html
    environment:
      - DATABASE_URL=mysql://cakephp_user:cakephp_password@ttt_mysql_1/cakephp_db
    networks:
      - bootapp


  mysql:
    # image: mysql:latest
    build:
      context: .
      dockerfile: Dockerfile.mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: cakephp_db
      MYSQL_USER: cakephp_user
      MYSQL_PASSWORD: cakephp_password
    ports:
        - "3307:3306"
    networks:
      - bootapp
  
  phpmyadmin:
    image: phpmyadmin:latest
    links:
      - mysql
    restart: always
    ports:
      - "9001:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password

volumes:
  mysql_data:
  
networks:
  bootapp: