# start with base image
FROM mysql:latest
# import data into conainer
# All scripts in docker-entrypoint-initdb.d/ are automatically executed during container startup
COPY cake_cms.sql /docker-entrypoint-initdb.d/
# COPY ./sql/users.sql /docker-entrypoint-initdb.d/